version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/project/zip/
    overwrite: yes

permission:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AppicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user