spring:
  profiles:
    group:
      "real2": "real-db,oauth"
---
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: native



spring:
  config:
    activate:
      on-profile: "real2"

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        enabled: true
        cache: false
