spring:
  profiles:
    include:
      - oauth
      - aws
#  session:
#    store-type: jdbc
#    jdbc.initialize-schema: always

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
      username: sa

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQL57Dialect
        # format_sql: true
        format_sql: false
        use_sql_comment: false
        default_batch_fetch_size: 100
    open-in-view: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true

logging.level:
  org.hibernate.SQL: info
  # org.hibernate.type: trace
  p6spy : info

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

decorator:
  datasource:
    p6spy:
      enable-logging: true