server:
  port: 8082

spring:
  profiles:
    group:
      "real2": "real-db"
---
spring:
  config:
    activate:
      on-profile: "real2"

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter: enabled

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

  server:
    servlet:
      encoding:
        charset: UTF-8
