spring:
  profiles:
    include: real-db

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter: enabled

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

#  server:
#    servlet:
#      encoding:
#        charset: UTF-8
