spring:
  profiles:
    group:
      "real": "real-db,oauth,aws"
---
spring:
  config:
    activate:
      on-profile: "real"

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: native
